apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: full-stack
spec:
  selector:
    app: frontend-ui
  ports:
    - name: http-web # <--- AÃ‘ADE ESTO (El nombre)
      port: 80 # El puerto del Servicio (ClusterIP)
      targetPort: 8080 # El puerto del Contenedor
