apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - database/pvc.yaml
  - database/configmap.yaml
  - database/deployment.yaml
  - database/service.yaml
  - database/rbac.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/route.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/route.yaml